import Head from 'next/head'
import EmlaCarouselContainer from '../components/embla-carousel-container'
import Features from '../components/features'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ngân hàng thương mại điện tử</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <EmlaCarouselContainer />
        <div className="main-content max-w-[1200px] mx-auto">
          <Features />
        </div>
      </main>
    </div>
  )
}
