import Head from 'next/head'
import EmlaCarouselContainer from '../components/embla-carousel-container'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ngân hàng thương mại điện tử</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <EmlaCarouselContainer />
      </main>
    </div>
  )
}
