import { PrismaClient } from '@prisma/client'
import Head from 'next/head'
import EmlaCarouselContainer from '../components/embla-carousel-container'
import Endow from '../components/endow'
import Features from '../components/features'
import Footer from '../components/footer'
import Sidebar from '../components/interest-rate-sidebar'
import Favicon from '../public/favicon.svg'


export default function Home(props: any) {
  const { users } = props
  console.log('home compo');
  console.log(users);

  return (
    <div>
      <Head>
        <title>Ngân hàng thương mại điện tử</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="mask-icon" href={Favicon} />
      </Head>
      <main>
        <EmlaCarouselContainer />
        <div className="main-content max-w-[1200px] px-[15px] mx-auto">
          <Features />
          <div className="flex flex-wrap items-start mt-20 font-[600]">
            <Sidebar />
            <Endow />
          </div>
        </div>
        <Footer />
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  const prisma = new PrismaClient()
  const users = await prisma.users.findMany()
  console.log(`user of prisma sqlite`);
  console.log(typeof users);
  console.log(users);

  return {
    props: { users }
  }
}
